<?php
// Démarrez la session au début de chaque page PHP
session_start();
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="../css/CGU.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/normalize.css">
    <link rel="icon" type="image/x-icon" href="../../images/TransNoise.ico">
    <title>C.G.U - EchoKey</title>

</head>
<body>
<header>
<nav>
    <ul class="menu">
      <li><a href="index.php">Home</a></li>
      <li><a href="analyse.php">Analysis</a></li>
      <li><a href="faq.php">Faq</a></li>
      <li><a href="espaceuser.php">Profile</a></li>
    </ul>
</nav>
<div class="loupebar"> <input type="text" id="searchInput" placeholder="Search..."> <div class="search"></div></div>
</header>

<a href="index.php"><img src="../../images/EchoKey_extrude.png" id="Logo1" alt="Logo EchoKey" title="Logo EchoKey"></a> <!--logo EchoKey-->

    <h1>Terms and Conditions of Use - EchoKey</h1>

    <div class="section">
        <h2>1. Use of the Service</h2>
        <p>1.1. By using EchoKey, you explicitly and consensually agree to these Terms and Conditions of Use.</p>
        <p>1.2. EchoKey is a voice service developed by TransNoise for the client Events-IT. This service uses the user's voice to provide personalized statistics based on their use of the site.</p>
    </div>

    <div class="section">
        <h2>2. Privacy and Data Use</h2>
        <p>2.1. The user's voice is recorded and used only for the generation of personalized statistics. All voice data collected remain confidential and are not shared with third parties without the user's explicit consent.</p>
        <p>2.2. TransNoise commits to using voice data only for the generation of statistics and not to exploit them for purposes other than those mentioned in these conditions.</p>
    </div>

    <div class="section">
        <h2>3. Responsibilities</h2>
        <p>3.1. The user agrees to use EchoKey in accordance with the law and not to compromise the confidentiality of their own voice. Events-IT is held responsible for the use of the service in its activities in accordance with these conditions.</p>
        <p>3.2. TransNoise takes appropriate security measures to protect EchoKey users' voice data from misuse or unauthorized use.</p>
    </div>

    <div class="section">
        <h2>4. Changes to the Terms</h2>
        <p>4.1. TransNoise reserves the right to modify these Terms and Conditions of Use at any time. Events-IT will be informed of any significant changes to these conditions.</p>
    </div>


    <footer class="mentions-legales">
        <h2>Legal Notice:</h2>
        <p>EchoKey is a service developed by TransNoise for the client Events-IT.</p>
        <p>All use of this service is governed by these General Terms and Conditions of Use.</p>
        <p>TransNoise is responsible for the collection and processing of voice data in accordance with current laws.</p>
        <p>Events-IT is the recipient of the statistics generated by the EchoKey service.</p>
        <br><br><br><br><br><br>
    </footer>

    <img src="../../images/collage.png" id="LogosFooter" alt="LogosFooter" title="LogosFooter"> <!--logo Transnoise-->
<footer>
  <div class="footer">
  <nav>
    <ul>
      <li><a href="CGU.php" target="_blank">T&Cs</a></li>
      <li><a href="https://www.isep.fr/" target="_blank">Our Investors</a></li>
      <li><a href="faq.php" target="_blank">Contact</a></li>
    </ul>
  </nav>
</div>
</footer>

<script src="../js/CGU.js"></script>
</body>
</html>
