CREATE TABLE topics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_User INT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_User) REFERENCES user(id_User)
);

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_User INT,
    topic_id INT,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_User) REFERENCES user(id_User),
    FOREIGN KEY (topic_id) REFERENCES topics(id)
);

ALTER TABLE topics ADD FOREIGN KEY(topic_by) REFERENCES user(id_User) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE posts ADD FOREIGN KEY(post_topic) REFERENCES topics(topic_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE posts ADD FOREIGN KEY(post_by) REFERENCES user(id_User) ON DELETE RESTRICT ON UPDATE CASCADE;
